### ISSUE TITLE
Main Scoutfish Repo

### ISSUE THREAD

**Issue by Rodeoclash** [gbtami/scoutfish#5]
Hi @gbtami 

Two small questions. Do you know if the Scoutfish repo (https://github.com/mcostalba/scoutfish) has a new home? I can see you've had some activity on it. I've raised a PR here: https://github.com/mcostalba/scoutfish/pull/49 to update some documentation but I don't have much confidence it will be merged.

My second question is that given you've contributed to the codebase already, how difficult do you think it will be to fix https://github.com/mcostalba/scoutfish/issues/45? I'm not a C++ developer but that feature would enable me to complete some analytics I'm doing on the Lichess database (https://github.com/Rodeoclash/chess_analysis). Essentially I'm trying to analyse if obtaining particular positions, e.g. the https://en.wikipedia.org/wiki/Mar%C3%B3czy_Bind) lead to a greater win chance for the player.

**Comment by gbtami** [comment]
As I remember Marco lost his interest to this project, so it is abandoned.

As I know scoutfish has no problem parsing lichess PGN files. At least if it contains standard chess games only.  Variants are not supported by scoutfish IIRC.

**Comment by Rodeoclash** [comment]
Ok, that's a shame. Thanks for letting me know though :slightly_smiling_face:
